version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    ports:
      - '3306:3306'
    volumes:
      - ./db/conf:/etc/mysql/conf.d/:ro
      - mysql_data:/var/lib/mysql
      - ./db/logs:/var/log/mysql
    networks:
      - backend

  api:
    image: node
    # environment:
    #   - MYSQL_SERVER=db
    #   - MYSQL_USER=${DB_USER}
    #   - MYSQL_PASSWORD=${DB_PASS}
    #   - MYSQL_DATABASE=${DB_NAME}
    #   - TZ=${TZ}
    #   - CHOKIDAR_USEPOLLING=true
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./api:/app
    working_dir: /app
    command: yarn run dev
    networks:
      - backend
    depends_on:
      - db

  react:
    image: node
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    ports:
      - '8080:8080'
    volumes:
      - ./front:/app
    working_dir: /app
    command: bash -c 'yarn start'
    networks:
      - backend
    depends_on:
      - api

networks:
  backend:
    name: app_network
    driver: bridge
    external: true

volumes:
  mysql_data:
